'use strict';

const http = require('http');
const os = require('os');
const fs = require('fs');
const path = require('path');
const { calculateOrderTotal } = require('./lib/pricing');

const PORT = process.env.PORT || 3000;
const pkg = require('./package.json');

// build-info.json is generated by CodeBuild; it will not exist on a laptop
function readBuildInfo() {
  try {
    const raw = fs.readFileSync(path.join(__dirname, 'build-info.json'), 'utf8');
    return JSON.parse(raw);
  } catch (err) {
    return { build: 'local', commit: 'local', builtAt: 'n/a' };
  }
}

const demoCart = [
  { sku: 'AVX-LAPTOP', price: 55000, qty: 2 },
  { sku: 'AVX-MOUSE', price: 799.5, qty: 4 }
];

function sendJson(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

function homePage(info) {
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Avox Order Pricing</title>
<style>
 body{font-family:Arial,sans-serif;background:#232f3e;color:#fff;text-align:center;padding-top:60px}
 .card{background:#fff;color:#232f3e;display:inline-block;padding:30px 50px;border-radius:10px;border-top:8px solid #ff9900}
 h1{margin:0 0 10px} .v{color:#ff9900;font-size:22px;font-weight:bold}
</style></head>
<body><div class="card">
 <h1>Avox IT Services - Order Pricing App</h1>
 <p class="v">Version ${pkg.version}</p>
 <p>Build #${info.build} | Commit ${String(info.commit).substring(0, 7)}</p>
 <p>Served by host: ${os.hostname()}</p>
 <p>Deployed by AWS CodePipeline &rarr; CodeBuild &rarr; CodeDeploy</p>
</div></body></html>`;
}

function createServer() {
  return http.createServer((req, res) => {
    const url = new URL(req.url, 'http://localhost');
    if (url.pathname === '/health') {
      return sendJson(res, 200, { status: 'UP', version: pkg.version });
    }
    if (url.pathname === '/api/info') {
      return sendJson(res, 200, { app: pkg.name, version: pkg.version,
        host: os.hostname(), ...readBuildInfo() });
    }
    if (url.pathname === '/api/quote') {
      return sendJson(res, 200, { cart: demoCart, ...calculateOrderTotal(demoCart) });
    }
    if (url.pathname === '/') {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      return res.end(homePage(readBuildInfo()));
    }
    return sendJson(res, 404, { error: 'Not Found' });
  });
}

if (require.main === module) {
  createServer().listen(PORT, () => {
    console.log(`avox-web-app v${pkg.version} listening on port ${PORT}`);
  });
}

module.exports = { createServer };
